# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:

with builtins;
with lib;

let
  unpackZigArtifact =
    { name, artifact }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig ];
      }
      ''
        hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash" "$out"
        chmod 755 "$out"
      '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = splitString "#" url;
      url_base = elemAt parts 0;
      url_without_query = elemAt (splitString "?" url_base) 0;
      rev_base = elemAt parts 1;
      rev = if match "^[a-fA-F0-9]{40}$" rev_base != null then rev_base else "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
    }:
    let
      parts = splitString "://" url;
      proto = elemAt parts 0;
      path = elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "12206cc206e9c206768d5813460cd0646a59fb395aff281cf8da2b026e1ec56b0828";
    path = fetchZigArtifact {
      name = "zig_gobject";
      url = "https://github.com/ianprime0509/zig-gobject/archive/e459534e05f40b536568a8b20394d7c06e441c98.tar.gz";
      hash = "sha256-tI7EHmulD7Y48We+R92E7vB1JLkJXfa59Uj7F8pSnso=";
    };
  }
  {
    name = "1220bb518b3fa657bb6b857a0b706e06012ca0b78ade85b90796a32d4c96b0c18185";
    path = fetchZigArtifact {
      name = "xml";
      url = "git+https://github.com/ianprime0509/zig-xml?ref=main#836821974ef608b23991c0602a5986f08939d88c";
      hash = "sha256-nrKBoMAa0DRTROoT59GneGX83jRAjCeLdBtc62sM+O0=";
    };
  }
]
