on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Version
        id: version
        run: echo "version=$(TZ=UTC date +%Y-%m-%d)-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build
        run: nix develop -c zig build -Dversion=${{ steps.version.outputs.version }}

      - name: Create Tarball
        run: nix develop -c tar --verbose --create --file ghostty-gobject-${{ steps.version.outputs.version}}.tar.zst --directory zig-out ghostty-gobject-${{ steps.version.outputs.version}}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: nix develop -c gh release create ${{ steps.version.outputs.version }} --latest --title ${{ steps.version.outputs.version }} ./ghostty-gobject-${{ steps.version.outputs.version}}.tar.zst
