on:
  push: {}
  pull_request: {}

name: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: nix run .#release
